logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

auth:
  jwt:
    secret: aWx1aXNkZmxpYW5maWZtczEyMzEyMzE0emxtY3p4Y2tvc2FrbWRvYWtkbW0xMjMxNTQzNjQ2NQ==
  accessToken:
    expiration: 86400000
  refreshToken:
    expiration: 1209600000

cookie:
  domain: localhost
  max-age: 345600