logging:
  level:
    root: info

spring:
  datasource:
    url: jdbc:h2:mem:tasker
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: never

auth:
  jwt:
    secret: aWx1aXNkZmxpYW5maWZtczEyMzEyMzE0emxtY3p4Y2tvc2FrbWRvYWtkbW0xMjMxNTQzNjQ2NQ==
  accessToken:
    expiration: 86400000
  refreshToken:
    expiration: 1209600000

cookie:
  domain: localhost
  max-age: 345600